### ISSUE TITLE
Overview logic #2 - Stars

### ISSUE THREAD

**Issue by kemp3673** [RFC2205-Himalia/Front_End_Capstone#41]
https://github.com/RFC2205-Himalia/Front_End_Capstone/blob/652a80211a8c3e065b1e28ef9bf334ad35495ac1/client/src/components/Overview/Product%20Details/Stars.jsx#L1-L11

No Stars were created. There is already a stars component made and used within the review widget. For code size and ease of writing just link that in your code instead of creating a new function. WIll also make the stars uniform across the page.

**Comment by tinyfishbigpond** [comment]
Got it put in
